# Generated by Django 5.2.1 on 2025-06-17 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(choices=[(1, '1 minute'), (5, '5 minutes'), (10, '10 minutes'), (30, '30 minutes'), (60, '1 hour')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response_time_threshold', models.IntegerField(default=500, help_text='Response time threshold in milliseconds', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(20000)])),
                ('expected_status', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(599)])),
                ('check_ssl', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredurl')),
            ],
        ),
        migrations.CreateModel(
            name='URLStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('is_up', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='monitor.monitoredurl')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.urlstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
