# Generated by Django 5.2.1 on 2025-06-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('scroll_depth', models.FloatField()),
                ('interactions', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredurl')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('requests', models.PositiveIntegerField()),
                ('bandwidth', models.FloatField()),
                ('status_distribution', models.JSONField()),
                ('unique_visitors', models.PositiveIntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredurl')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('path_sequence', models.JSONField()),
                ('timestamp_start', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField()),
                ('exit_page', models.CharField(max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredurl')),
            ],
        ),
    ]
