# Generated by Django 5.2.1 on 2025-10-24 16:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_engagement_trafficmetric_userflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="session_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="monitoredurl",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="monitoredurl",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="trafficmetric",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="urlstatus",
            name="is_up",
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name="urlstatus",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="userflow",
            name="session_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userflow",
            name="timestamp_start",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["url", "is_active"], name="monitor_ale_url_id_76b094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagement",
            index=models.Index(
                fields=["url", "-timestamp"], name="monitor_eng_url_id_f3dcb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoredurl",
            index=models.Index(
                fields=["user", "is_active"], name="monitor_mon_user_id_17e96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoredurl",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="monitor_mon_is_acti_5bda88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="monitor_not_user_id_23f2f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trafficmetric",
            index=models.Index(
                fields=["url", "-timestamp"], name="monitor_tra_url_id_342ec4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urlstatus",
            index=models.Index(
                fields=["url", "-timestamp"], name="monitor_url_url_id_b95593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urlstatus",
            index=models.Index(
                fields=["url", "is_up", "timestamp"],
                name="monitor_url_url_id_5230a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userflow",
            index=models.Index(
                fields=["url", "-timestamp_end"], name="monitor_use_url_id_17fd70_idx"
            ),
        ),
    ]
