# Generated by Django 5.2.1 on 2025-10-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitor",
            "0005_clickheatmap_conversionfunnel_mousemovement_pageview_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clickheatmap",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="click_heatmaps",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="conversionfunnel",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversion_funnels",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="mousemovement",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mouse_movements",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_views",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="performancemetric",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_metrics",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="scrollheatmap",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scroll_heatmaps",
                to="monitor.monitoredurl",
            ),
        ),
        migrations.AlterField(
            model_name="sessionrecording",
            name="url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_recordings",
                to="monitor.monitoredurl",
            ),
        ),
    ]
